/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tienda.vista;

import com.mycompany.tienda.vista.MainConSesion;
import com.mycompany.tienda.Cliente;
import com.mycompany.tienda.Cliente;
import com.mycompany.tienda.control.ControlClientes;
import java.util.Map;
/**
 *
 * @author samue
 */
public class ListaClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListaClientes.class.getName());
    
    private ControlClientes controlClientes;

    /**
     * Creates new form ListUserForm
     * @param controlClientes
     */
    public ListaClientes(ControlClientes controlClientes) {
        initComponents();
        
        this.controlClientes = ControlClientes.getInstancia();
        // Cargar clientes en el combo
        cargarClientes();
    }

    private ListaClientes() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void cargarClientes() {
        // Limpiar el combo antes de cargar
        usersCombo.removeAllItems();
        
        // Obtener los clientes
        Map<String, Cliente> clientes = controlClientes.getClientes();
        
        // DEBUG: Ver cuántos clientes hay
        System.out.println("========= DEBUG =========");
        System.out.println("Total de clientes: " + clientes.size());
        
        if (clientes.isEmpty()) {
            System.out.println(" No hay clientes en el HashMap");
            usersCombo.addItem("No hay clientes registrados");
        } else {
            // Llenar el combo con los nombres
            for (Cliente cliente : clientes.values()) {
                System.out.println("Cliente encontrado: " + cliente.getNombre());
                usersCombo.addItem(cliente.getNombre());
            }
        }
        System.out.println("========================");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        usersCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lista de clientes");

        cancelBtn.setText("Volver");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        usersCombo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                usersComboComponentMoved(evt);
            }
        });
        usersCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn))
                        .addGap(0, 224, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        MainConSesion cuf = new MainConSesion();
        cuf.setVisible(true);
        ListaClientes.this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void usersComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersComboActionPerformed
        // TODO add your handling code here:
        String nombreSeleccionado = (String) usersCombo.getSelectedItem();
        if (nombreSeleccionado != null && !nombreSeleccionado.equals("No hay clientes registrados")) {
            System.out.println("Cliente seleccionado: " + nombreSeleccionado);
        }
    }//GEN-LAST:event_usersComboActionPerformed

    private void usersComboComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_usersComboComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_usersComboComponentMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListaClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> usersCombo;
    // End of variables declaration//GEN-END:variables
}
