/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tienda.vista;

/**
 *
 * @author samue
 */

public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        SupervisorIniciarS = new javax.swing.JMenuItem();
        TecnicoInicioS = new javax.swing.JMenu();
        VendedorInicioS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel1.setText("Para poder acceder a los productos debes iniciar sesion");

        jMenu2.setText("Inicio sesion");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenu3.setText("Iniciar sesion Empleado");

        SupervisorIniciarS.setText("Supervisor");
        SupervisorIniciarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupervisorIniciarSActionPerformed(evt);
            }
        });
        jMenu3.add(SupervisorIniciarS);

        TecnicoInicioS.setText("Tecnico");
        TecnicoInicioS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TecnicoInicioSMouseClicked(evt);
            }
        });
        jMenu3.add(TecnicoInicioS);

        VendedorInicioS.setText("Cajero");
        VendedorInicioS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendedorInicioSActionPerformed(evt);
            }
        });
        jMenu3.add(VendedorInicioS);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VendedorInicioSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendedorInicioSActionPerformed
        // TODO add your handling code here:
        Iniciar_Sesion cuf = new Iniciar_Sesion();
        cuf.setVisible(true);
        Main.this.dispose();
    }//GEN-LAST:event_VendedorInicioSActionPerformed

    private void SupervisorIniciarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupervisorIniciarSActionPerformed
        // TODO add your handling code here:
        IniciarSesionS cuf = new IniciarSesionS();
        cuf.setVisible(true);
        Main.this.dispose();
    }//GEN-LAST:event_SupervisorIniciarSActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void TecnicoInicioSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TecnicoInicioSMouseClicked
        // TODO add your handling code here:
        IniciarSesionT tecLogin = new IniciarSesionT();
        tecLogin.setVisible(true);
        Main.this.dispose();
    }//GEN-LAST:event_TecnicoInicioSMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SupervisorIniciarS;
    private javax.swing.JMenu TecnicoInicioS;
    private javax.swing.JMenuItem VendedorInicioS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
